### ISSUE TITLE
Printer stopped working

### ISSUE THREAD

**Issue by LewisHarryRennison** [garynmckinney/3DPrinter#3]
Hi their i bought the Prusa i3 3D Printer Kit w/SD-Card Reader / USB 2.0 Bundle for £205.73 a little while ago. But this morning when I started it up the power pack green light did dont come on and the printer would not come to life. I have tried to give it power through another power pack that give 12V DC 20 A but still nothing.

I don't know what to do can you help me please.

**Comment by BradDudenhoffer** [comment]
It could be a fried control board. If you connect USB without the poster supply do you get a solid red light on the board and a blue that flashes a couple times?

**Comment by LewisHarryRennison** [comment]
OK thanks for the idea I have connected it to the pc and it all came to life and the screen came on so I looked at the voltage the power packs where giving and it was 0V so I have bought a new power pack and I hope this works. It is meant to arrive in 2 to 3 days. So I will know soon.

thanks
lewis

**Comment by LewisHarryRennison** [comment]
Ok the new power pack has arrived and works but the 3d printer still not working. I don't know what to do know? can you help?

**Comment by BradDudenhoffer** [comment]
That's not a good sign. Are there any obviously burned components on or odd smells coming from the control board? Will your PC connect to the board? Can you control the motors or heaters?

**Comment by LewisHarryRennison** [comment]
when i connect it to the Pc the screen does come on and the screen say the temps of the bed and nosel.
they are no smells from the mother board. I don't know if the motes work as i am on holiday for the next 3 days but i know they are no smells and the screen comes on when it it pugled into the pc.

**Comment by BradDudenhoffer** [comment]
It is starting to sound more like the control board, or at least part of it, has failed. I would suggest trying to move the motors and powering the heaters from the control board but I would bet you need a new one. I cont remember the model at the moment but I did check them before buying the printer kit and they are fairly inexpensive on eBay or aliexpress.

**Comment by LewisHarryRennison** [comment]
Yes they are but i could not find the v3.0 of the control panel/motherboard which is what mine is.
Can you find on for me so i know what I am looking for than you.

lewis

**Comment by LewisHarryRennison** [comment]
Just as a question do you think that i will get a new on form the company as I only ordered it on the (14 Nov, 2015) and i don't see how i could have broken it?

**Comment by BradDudenhoffer** [comment]
They may replace it but I have found that many of those companies don't honor any kind of warranty. It's definitely worth contacting them to see what they will do.

**Comment by BradDudenhoffer** [comment]
I'm pretty sure mine is a MKS board version 1.3. It looks like they are around US$40.

**Comment by LewisHarryRennison** [comment]
Ok i will try. Thank you.

**Comment by LewisHarryRennison** [comment]
OK they are going to send me a new one lets hope that works..

Thanks
Lewis
